// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uggzpiytpykmfuubstfn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVnZ3pwaXl0cHlrbWZ1dWJzdGZuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0ODg1MjEsImV4cCI6MjA3MzA2NDUyMX0.qq0JlKAoFCEweMqgWCQ2q7djCfkjowzZKk55cHR9PVg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});